// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Dn9m17tvspQmEO4Rht0SQG9dA7p9yDM',
    appId: '1:720594078751:web:e6bf6f0641fb7f318bd92a',
    messagingSenderId: '720594078751',
    projectId: 'todoapp-e4ac9',
    authDomain: 'todoapp-e4ac9.firebaseapp.com',
    storageBucket: 'todoapp-e4ac9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwDAGMN8nD5KrJ8HU5Usrg0dk6rT0hL0',
    appId: '1:720594078751:android:1e98736c18c480bc8bd92a',
    messagingSenderId: '720594078751',
    projectId: 'todoapp-e4ac9',
    storageBucket: 'todoapp-e4ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00OwXvhRdOxGLqquK_pNsOVByVJN7s9g',
    appId: '1:720594078751:ios:b59b1e298e5440c98bd92a',
    messagingSenderId: '720594078751',
    projectId: 'todoapp-e4ac9',
    storageBucket: 'todoapp-e4ac9.appspot.com',
    iosBundleId: 'com.enit.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00OwXvhRdOxGLqquK_pNsOVByVJN7s9g',
    appId: '1:720594078751:ios:b59b1e298e5440c98bd92a',
    messagingSenderId: '720594078751',
    projectId: 'todoapp-e4ac9',
    storageBucket: 'todoapp-e4ac9.appspot.com',
    iosBundleId: 'com.enit.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Dn9m17tvspQmEO4Rht0SQG9dA7p9yDM',
    appId: '1:720594078751:web:2a6e62a774b519008bd92a',
    messagingSenderId: '720594078751',
    projectId: 'todoapp-e4ac9',
    authDomain: 'todoapp-e4ac9.firebaseapp.com',
    storageBucket: 'todoapp-e4ac9.appspot.com',
  );
}
